name: 'Setup Node Env, Get & Cache Dependencies'
description: 'Setup Node Env, Get & Cache Dependencies(via yarn) for faster builds'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - name: Setup node env 🏗
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: 'Cache Dependencies 🕓'
      uses: 'actions/cache@v4'
      id: cache-node-modules
      with:
        path: 'node_modules'
        key: deps-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install Dependencies 👨🏻‍💻
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: pnpm install  --no-frozen-lockfile
      shell: bash
